

preprocess:
  raw_root: data/raw
  out_root: data/processed
  val_size: 0.1
  seed: 101

hyperparams:
  img_size: 64
  batch_size: 64
  num_workers: 4
  dropout: 0.4
  epochs: 10
  lr: 0.0001

dagshub:
 repo_owner: RePlay-h
 repo_name: TrafficSignNet
 mlflow_uri: https://dagshub.com/RePlay-h/TrafficSignNet.mlflow

train:
  seed: 101


  